"""Chat API — 对齐 Java ChatController + SessionEventController"""
import asyncio
import json
import logging
from fastapi import APIRouter, Depends, HTTPException, Query, Body, Response
from fastapi.responses import HTMLResponse, StreamingResponse
from sqlalchemy.ext.asyncio import AsyncSession
from typing import Optional, Dict, Any
from datetime import datetime

from ..core.database import get_db
from ..services.chat_service import ChatService
from ..services.agent_service import AgentService
from ..services.session_event_publisher import SessionEventPublisher
from ..schemas.chat_session import ChatSessionCreateRequest, ChatSessionResponse
from ..schemas.chat_message import ChatMessageCreateRequest, ChatMessageResponse

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api", tags=["Chat会话"])

# HTML report template (minimal)
REPORT_HEADER = """<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>数据分析报告</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 900px; margin: 0 auto; padding: 20px; color: #333; }
  h1 { border-bottom: 2px solid #4A90D9; padding-bottom: 10px; }
  table { border-collapse: collapse; width: 100%; margin: 15px 0; }
  th, td { border: 1px solid #ddd; padding: 8px 12px; text-align: left; }
  th { background: #4A90D9; color: white; }
  pre { background: #f5f5f5; padding: 15px; border-radius: 5px; overflow-x: auto; }
  .footer { margin-top: 30px; padding-top: 15px; border-top: 1px solid #eee; color: #999; font-size: 12px; }
</style>
</head>
<body>
"""
REPORT_FOOTER = '<div class="footer">Generated by DataAgent Python @ {}</div></body></html>'


def _session_to_response(session) -> dict:
    return ChatSessionResponse.model_validate(session).model_dump(by_alias=True)


def _message_to_response(message) -> dict:
    return ChatMessageResponse.model_validate(message).model_dump(by_alias=True)


# ==================================================================
# Session APIs — /api/agent/{id}/sessions
# ==================================================================

@router.get("/agent/{agent_id}/sessions", summary="获取会话列表")
async def list_sessions(agent_id: int, db: AsyncSession = Depends(get_db)):
    """获取 Agent 的所有会话 — 对齐 Java getAgentSessions"""
    agent = await AgentService.get_agent(db, agent_id)
    if not agent:
        raise HTTPException(status_code=404, detail="Agent 不存在")
    sessions = await ChatService.list_sessions(db, agent_id)
    return [_session_to_response(s) for s in sessions]


@router.post("/agent/{agent_id}/sessions", status_code=201, summary="创建会话")
async def create_session(
    agent_id: int,
    body: Optional[ChatSessionCreateRequest] = None,
    db: AsyncSession = Depends(get_db),
):
    """创建新会话 — 对齐 Java createSession"""
    agent = await AgentService.get_agent(db, agent_id)
    if not agent:
        raise HTTPException(status_code=404, detail="Agent 不存在")
    title = body.title if body else "新对话"
    user_id = body.user_id if body else None
    session = await ChatService.create_session(db, agent_id, title=title, user_id=user_id)
    return _session_to_response(session)


@router.delete("/agent/{agent_id}/sessions", summary="清空会话")
async def clear_sessions(agent_id: int, db: AsyncSession = Depends(get_db)):
    """清空 Agent 的所有会话 — 对齐 Java clearAgentSessions"""
    agent = await AgentService.get_agent(db, agent_id)
    if not agent:
        raise HTTPException(status_code=404, detail="Agent 不存在")
    count = await ChatService.clear_sessions(db, agent_id)
    return {"success": True, "message": f"已清空 {count} 个会话", "data": None}


@router.get("/agent/{agent_id}/sessions/stream", summary="SSE 会话事件流")
async def stream_session_events(agent_id: int, db: AsyncSession = Depends(get_db)):
    """SSE 端点：推送会话标题更新等事件 — GET /api/agent/{agentId}/sessions/stream"""
    agent = await AgentService.get_agent(db, agent_id)
    if not agent:
        raise HTTPException(status_code=404, detail="Agent 不存在")

    queue = await SessionEventPublisher.register(agent_id)

    async def event_generator():
        try:
            while True:
                try:
                    event = await asyncio.wait_for(queue.get(), timeout=2.0)
                    data = event.model_dump(by_alias=True)
                    yield f"event: {event.type}\ndata: {json.dumps(data, ensure_ascii=False)}\n\n"
                except asyncio.TimeoutError:
                    yield ": heartbeat\n\n"
        except asyncio.CancelledError:
            pass
        finally:
            await SessionEventPublisher.unregister(agent_id, queue)

    return StreamingResponse(
        event_generator(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "Access-Control-Allow-Origin": "*",
        },
    )


# ==================================================================
# Message APIs — /api/sessions/{sessionId}/messages
# ==================================================================

@router.get("/sessions/{session_id}/messages", summary="获取消息列表")
async def list_messages(session_id: str, db: AsyncSession = Depends(get_db)):
    """获取会话的所有消息 — 对齐 Java getSessionMessages"""
    session = await ChatService.get_session(db, session_id)
    if not session:
        raise HTTPException(status_code=404, detail="会话不存在")
    messages = await ChatService.list_messages(db, session_id)
    return [_message_to_response(m) for m in messages]


@router.post("/sessions/{session_id}/messages", status_code=201, summary="保存消息")
async def save_message(
    session_id: str,
    request: ChatMessageCreateRequest,
    db: AsyncSession = Depends(get_db),
):
    """保存消息到会话 — 对齐 Java saveMessage"""
    session = await ChatService.get_session(db, session_id)
    if not session:
        raise HTTPException(status_code=404, detail="会话不存在")
    message = await ChatService.save_message(
        db, session_id,
        role=request.role,
        content=request.content,
        message_type=request.message_type,
        metadata=request.metadata,
    )
    # 对齐 Java: titleNeeded 时异步生成会话标题
    if request.title_needed and request.role == "user":
        from ..services.session_title_service import schedule_title_generation
        from ..core.database import async_session_factory
        asyncio.create_task(
            schedule_title_generation(
                session_id, session.agent_id, request.content, ChatService, async_session_factory
            )
        )
    return _message_to_response(message)


# ==================================================================
# Session 操作 APIs — /api/sessions/{sessionId}/...
# ==================================================================

@router.put("/sessions/{session_id}/pin", summary="置顶/取消置顶会话")
async def pin_session(
    session_id: str,
    isPinned: int = Query(..., description="1=置顶, 0=取消置顶"),
    db: AsyncSession = Depends(get_db),
):
    """置顶或取消置顶会话 — 对齐 Java pinSession"""
    session = await ChatService.get_session(db, session_id)
    if not session:
        raise HTTPException(status_code=404, detail="会话不存在")
    await ChatService.pin_session(db, session_id, isPinned)
    msg = "会话已置顶" if isPinned else "会话已取消置顶"
    return {"success": True, "message": msg, "data": None}


@router.put("/sessions/{session_id}/rename", summary="重命名会话")
async def rename_session(
    session_id: str,
    title: str = Query(..., min_length=1, description="新标题"),
    db: AsyncSession = Depends(get_db),
):
    """重命名会话 — 对齐 Java renameSession"""
    if not title.strip():
        raise HTTPException(status_code=400, detail="标题不能为空")
    session = await ChatService.get_session(db, session_id)
    if not session:
        raise HTTPException(status_code=404, detail="会话不存在")
    await ChatService.rename_session(db, session_id, title)
    return {"success": True, "message": "会话已重命名", "data": None}


@router.delete("/sessions/{session_id}", summary="删除会话")
async def delete_session(session_id: str, db: AsyncSession = Depends(get_db)):
    """删除单个会话 — 对齐 Java deleteSession"""
    success = await ChatService.delete_session(db, session_id)
    if not success:
        raise HTTPException(status_code=404, detail="会话不存在")
    return {"success": True, "message": "会话已删除", "data": None}


@router.post("/sessions/{session_id}/reports/html", summary="生成HTML报告")
async def download_html_report(
    session_id: str,
    content: str = Body(..., media_type="text/plain"),
    db: AsyncSession = Depends(get_db),
):
    """生成 HTML 报告并下载 — 对齐 Java convertAndDownloadHtml"""
    session = await ChatService.get_session(db, session_id)
    if not session:
        raise HTTPException(status_code=404, detail="会话不存在")
    if not content.strip():
        raise HTTPException(status_code=400, detail="内容不能为空")

    timestamp = datetime.now().strftime("%Y%m%d%H%M%S")
    filename = f"report_{timestamp}.html"
    html = REPORT_HEADER + content + REPORT_FOOTER.format(datetime.now().strftime("%Y-%m-%d %H:%M"))

    return HTMLResponse(
        content=html,
        headers={
            "Content-Disposition": f'attachment; filename="{filename}"',
        },
    )
